// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----------------------- //
// i2s_master_in_mono_left //
// ----------------------- //

#define i2s_master_in_mono_left_wrap_target 4
#define i2s_master_in_mono_left_wrap 19
#define i2s_master_in_mono_left_pio_version 0

#define i2s_master_in_mono_left_offset_entry_point 0u

static const uint16_t i2s_master_in_mono_left_program_instructions[] = {
    0xa842, //  0: nop                    side 1
    0xe83e, //  1: set    x, 30           side 1
    0xa042, //  2: nop                    side 0
    0xa042, //  3: nop                    side 0
            //     .wrap_target
    0xa842, //  4: nop                    side 1
    0x4801, //  5: in     pins, 1         side 1
    0xa042, //  6: nop                    side 0
    0x0044, //  7: jmp    x--, 4          side 0
    0xb842, //  8: nop                    side 3
    0x5801, //  9: in     pins, 1         side 3
    0xf03e, // 10: set    x, 30           side 2
    0xb042, // 11: nop                    side 2
    0xb842, // 12: nop                    side 3
    0xb842, // 13: nop                    side 3
    0xb042, // 14: nop                    side 2
    0x104c, // 15: jmp    x--, 12         side 2
    0xa842, // 16: nop                    side 1
    0xa842, // 17: nop                    side 1
    0xe03e, // 18: set    x, 30           side 0
    0xa042, // 19: nop                    side 0
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program i2s_master_in_mono_left_program = {
    .instructions = i2s_master_in_mono_left_program_instructions,
    .length = 20,
    .origin = -1,
    .pio_version = i2s_master_in_mono_left_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config i2s_master_in_mono_left_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + i2s_master_in_mono_left_wrap_target, offset + i2s_master_in_mono_left_wrap);
    sm_config_set_sideset(&c, 2, false, false);
    return c;
}

const int pio_i2s_master_in_program_mult = 4;
///////////////////////////////////////////////////////////////////////////////
static inline void i2s_master_in_mono_left_program_init(PIO pio, uint8_t sm, uint8_t offset, uint8_t bit_depth, uint8_t din_pin, uint8_t clock_pin_base) 
{
    pio_gpio_init(pio, din_pin);
    pio_gpio_init(pio, clock_pin_base);
    pio_gpio_init(pio, clock_pin_base + 1);
    gpio_pull_down(din_pin);
    pio_sm_config sm_config = i2s_master_in_mono_left_program_get_default_config(offset);
    sm_config_set_in_pins(&sm_config, din_pin);
    sm_config_set_sideset_pins(&sm_config, clock_pin_base);
    sm_config_set_in_shift(&sm_config, false, true, bit_depth);
    sm_config_set_fifo_join(&sm_config, PIO_FIFO_JOIN_RX);
    pio_sm_init(pio, sm, offset, &sm_config);
    // DIN as input
    // LRCLK and BCLK as output 
    uint32_t pin_dirs = (3u << clock_pin_base);  
    uint32_t pin_mask = (1u << din_pin) | (3u << clock_pin_base);  
    pio_sm_set_pins_with_mask(pio, sm, 0, pin_mask);  
    pio_sm_set_pindirs_with_mask(pio, sm, pin_dirs, pin_mask);
}

#endif

